<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\HistoryController' shared autowired service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\framework-bundle\\Controller\\ControllerTrait.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\framework-bundle\\Controller\\AbstractController.php';
include_once $this->targetDirs[3].'\\src\\Controller\\ApiController.php';
include_once $this->targetDirs[3].'\\src\\Controller\\HistoryController.php';
include_once $this->targetDirs[3].'\\src\\Service\\HistoryService.php';

$a = ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService());
$b = ($this->privates['App\\Repository\\HistoryRepository'] ?? $this->load('getHistoryRepositoryService.php'));

$this->services['App\\Controller\\HistoryController'] = $instance = new \App\Controller\HistoryController($a, $b, new \App\Service\HistoryService($b, $a));

$instance->setContainer(($this->privates['.service_locator.CDOTD6.'] ?? $this->load('get_ServiceLocator_CDOTD6_Service.php'))->withContext('App\\Controller\\HistoryController', $this));

return $instance;
