<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYbT2tAz\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYbT2tAz/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYbT2tAz.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYbT2tAz\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYbT2tAz\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'YbT2tAz',
    'container.build_id' => 'df06ef47',
    'container.build_time' => 1562690774,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYbT2tAz');
